import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import Link from 'next/link';
import { waterlooUgCourses, getWaterlooUgCourseBySlug } from '@/data/waterlooug-courses';
import { buildMetadata } from '@/lib/seo';
import LeadForm from '@/components/LeadForm';
import JsonLd from '@/components/JsonLd';
import CourseRichContent from '@/components/CourseRichContent';
import { showOnCoursePage } from '@/lib/course-field-variance';
import { feeDisplay, feeDisplayINRLakh, isFeeVerified, feeSentenceINR, titleFeeFragment } from '@/lib/fee-verification';
import { RATE_TO_INR, courseAnnualINRLakh } from '@/lib/currency';

// Generated by scripts/gen-canada-wave-routes.js — edit the generator, not this file.

/** Tests this university's own English-requirements page published a score for. */
const PUBLISHED_TESTS = {"ielts":true,"toefl":false,"pte":true};
function englishTests(c: any) {
  return [
    { label: 'IELTS Academic', value: c.ieltsMin, show: PUBLISHED_TESTS.ielts },
    { label: 'TOEFL iBT', value: c.toeflMin, show: PUBLISHED_TESTS.toefl },
    { label: 'PTE Academic', value: c.pteMin, show: PUBLISHED_TESTS.pte },
  ].filter((t) => t.show && Number(t.value) > 0 && !/house default|not published/i.test(c.englishScope || ''));
}
function englishScopeNote(c: any): string {
  return /institution/i.test(c.englishScope || '')
    ? 'University-wide minimum — some programmes set a higher score.'
    : 'Published on the programme page.';
}

const UNIVERSITY_SLUG = 'university-of-waterloo';

export function courseParams() {
  return (waterlooUgCourses as unknown as any[]).map((c) => ({ slug: c.slug }));
}

export async function courseMetadata(slug: string): Promise<Metadata> {
  const course = getWaterlooUgCourseBySlug(slug) as any;
  if (!course) return {};
  const english = englishTests(course).some((t) => t.label === 'IELTS Academic') ? ` IELTS ${course.ieltsMin}+.` : '';
  return buildMetadata({
    title: `${course.name} at University of Waterloo`,
    description: `${course.name} at University of Waterloo, Waterloo${feeSentenceINR(course, course.annualINR)}${english} Apply with Jaivik Overseas — 13 years expertise, 99% visa success.`,
    path: `/universities/university-of-waterloo/courses/${slug}`,
    keywords: [course.name, 'Waterloo', 'University of Waterloo', 'study in Canada', course.level],
  });
}

export default async function CourseView({ slug }: { slug: string }) {
  const course = getWaterlooUgCourseBySlug(slug) as any;
  if (!course) notFound();

  const verified = isFeeVerified(course);
  const feeINRLakh = courseAnnualINRLakh(course, 1) ?? '0';
  const years = course.durationYears || 0;
  const schema = {
    '@context': 'https://schema.org',
    '@type': 'Course',
    name: course.name,
    provider: { '@type': 'CollegeOrUniversity', name: 'University of Waterloo', sameAs: 'https://uwaterloo.ca' },
    courseMode: 'full-time',
    educationalLevel: course.studyLevel,
    ...(years > 0 ? { timeRequired: `P${years}Y` } : {}),
    url: course.url,
  };

  return (
    <>
      <JsonLd data={schema} />

      <section className="bg-gradient-to-br from-brand-700 to-brand-900 text-white py-14 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center gap-2 text-blue-200 text-xs mb-4 flex-wrap">
            <Link href="/" className="hover:text-white">Home</Link> /
            <Link href="/universities" className="hover:text-white">Universities</Link> /
            <Link href="/universities/country/canada" className="hover:text-white">Canada</Link> /
            <Link href="/universities/university-of-waterloo" className="hover:text-white">Waterloo</Link> /
            <Link href="/universities/university-of-waterloo/courses" className="hover:text-white">Courses</Link> /
            <span className="text-white">{course.name}</span>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
            <div className="lg:col-span-2">
              <div className="inline-flex items-center gap-2 bg-gold-500/20 text-gold-400 text-xs font-semibold px-3 py-1.5 rounded-full mb-4">
                🇨🇦 University of Waterloo · Waterloo, Canada
              </div>
              <h1 className="text-3xl md:text-4xl font-bold mb-3">{course.name} at University of Waterloo — {titleFeeFragment(course, course.annualINR)}Requirements for Indian Students</h1>
              <p className="text-blue-200 text-lg mb-5">{course.level} · {course.duration} · {course.campus}</p>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                {[
                  { label: 'Annual Fee (CAD)', value: feeDisplay(course, course.annualCAD, 'CAD') },
                  { label: 'Fee in INR', value: feeDisplayINRLakh(course, feeINRLakh, '/yr') },
                  ...(englishTests(course).some((t) => t.label === 'IELTS Academic') && showOnCoursePage(UNIVERSITY_SLUG, 'ieltsMin') ? [{ label: 'IELTS Minimum', value: `${course.ieltsMin}+` }] : []),
                  { label: 'Duration', value: course.duration },
                ].map((s) => (
                  <div key={s.label} className="bg-white/10 rounded-xl p-3 text-center">
                    <p className="text-lg font-bold">{s.value}</p>
                    <p className="text-xs text-blue-200 mt-1">{s.label}</p>
                  </div>
                ))}
              </div>
            </div>
            <div className="bg-white rounded-2xl p-5">
              <LeadForm source={`waterloo-ug-course-${slug}`} defaultCountry="Canada" compact />
            </div>
          </div>
        </div>
      </section>

      <div className="max-w-7xl mx-auto px-4 py-10 grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
            <h2 className="text-xl font-bold text-gray-900 mb-4">Course Overview</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {[
                { label: 'Qualification', value: course.level },
                { label: 'Duration', value: course.duration },
                ...(showOnCoursePage(UNIVERSITY_SLUG, 'campus') ? [{ label: 'Campus', value: course.campus }] : []),
                ...(showOnCoursePage(UNIVERSITY_SLUG, 'intakeMonths') && course.intakeMonths?.length ? [{ label: 'Intakes', value: course.intakeMonths.join(' & ') }] : []),
                { label: 'Annual Tuition (CAD)', value: feeDisplay(course, course.annualCAD, 'CAD') },
                { label: 'Annual Tuition (USD)', value: feeDisplay(course, course.annualUSD, 'USD') },
              ].map((f) => (
                <div key={f.label} className="p-4 bg-gray-50 rounded-xl">
                  <p className="text-xs text-gray-500 font-medium mb-1">{f.label}</p>
                  <p className="text-sm font-semibold text-gray-900">{f.value}</p>
                </div>
              ))}
            </div>
            {verified && course.feeBasis && (
              <p className="text-xs text-gray-500 mt-4">
                Fee basis: {course.feeBasis}.{' '}
                {course.feeSourceUrl && <a href={course.feeSourceUrl} target="_blank" rel="noopener noreferrer" className="text-brand-700 hover:underline">Source ↗</a>}
              </p>
            )}
          </div>

          <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
            <h2 className="text-xl font-bold text-gray-900 mb-4">English Language Requirements</h2>
            {englishTests(course).length > 0 ? (
              <>
                <div className="grid grid-cols-3 gap-4">
                  {englishTests(course).map((e) => (
                    <div key={e.label} className="bg-blue-50 rounded-xl p-4 text-center">
                      <p className="text-xl font-bold text-brand-700">{e.value}+</p>
                      <p className="text-xs font-semibold text-gray-700 mt-1">{e.label}</p>
                    </div>
                  ))}
                </div>
                <p className="text-xs text-gray-500 mt-3">{englishScopeNote(course)}</p>
              </>
            ) : (
              <p className="text-sm text-gray-600">
                University of Waterloo doesn’t publish a single English score that applies to this programme.
                Ask us and we’ll confirm the IELTS, TOEFL or PTE score you need before you apply.
              </p>
            )}
          </div>

          {verified && years > 0 && !/first year/i.test(course.feeBasis || '') && (
            <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
              <h2 className="text-xl font-bold text-gray-900 mb-4">Estimated Cost of Study (Indian Students)</h2>
              <div className="space-y-3">
                {[
                  { label: `Tuition × ${years} year${years !== 1 ? 's' : ''}`, value: `$${course.totalCAD.toLocaleString()} CAD`, highlight: true },
                  { label: `Living cost estimate × ${years} year${years !== 1 ? 's' : ''}`, value: `$${(course.livingCostCAD * years).toLocaleString()} CAD` },
                  { label: 'Total estimate', value: `$${(course.totalCAD + course.livingCostCAD * years).toLocaleString()} CAD`, highlight: true },
                  { label: 'In Indian Rupees (₹)', value: `₹${((course.totalCAD + course.livingCostCAD * years) * RATE_TO_INR.CAD / 100000).toFixed(1)} Lakh`, highlight: true },
                ].map((r) => (
                  <div key={r.label} className={`flex justify-between items-center p-3 rounded-xl ${r.highlight ? 'bg-brand-50 font-bold' : 'bg-gray-50'}`}>
                    <span className="text-sm text-gray-700">{r.label}</span>
                    <span className={`text-sm ${r.highlight ? 'text-brand-700' : 'text-gray-900'}`}>{r.value}</span>
                  </div>
                ))}
              </div>
              <p className="text-xs text-gray-500 mt-3">Tuition can rise in later years. Living cost is our estimate, not a university figure.</p>
            </div>
          )}

          <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
            <h2 className="text-xl font-bold text-gray-900 mb-4">Study Permit &amp; Post-Graduation Work</h2>
            <p className="text-sm text-gray-700">Graduates of eligible programmes at designated learning institutions can apply for a Post-Graduation Work Permit. Its length depends on the length of the programme.</p>
          </div>

          <CourseRichContent course={course} universityName="University of Waterloo" universitySlug="university-of-waterloo" />

          <div className="bg-brand-700 rounded-2xl p-6 text-white text-center">
            <h2 className="text-xl font-bold mb-2">Interested in {course.name}?</h2>
            <p className="text-blue-200 text-sm mb-4">Book a free counselling session. Our Canada admissions advisors help Indian students every step of the way.</p>
            <Link href="/book-counselling" className="btn-gold inline-block">Get Free Guidance →</Link>
          </div>
        </div>

        <div className="space-y-5">
          <div className="sticky top-20">
            <LeadForm source={`waterloo-ug-course-${slug}-sidebar`} defaultCountry="Canada" />
            <div className="mt-4 bg-white rounded-2xl p-5 border border-gray-100 shadow-sm">
              <h3 className="font-bold text-gray-900 mb-3 text-sm">Related Links</h3>
              <div className="space-y-2">
                <a href={course.url} target="_blank" rel="noopener noreferrer" className="block text-sm text-brand-700 hover:underline">Official Course Page ↗</a>
                <Link href="/universities/university-of-waterloo/courses" className="block text-sm text-brand-700 hover:underline">All Waterloo Courses →</Link>
                <Link href="/universities/country/canada" className="block text-sm text-brand-700 hover:underline">Study in Canada Guide →</Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
