import { NextResponse } from 'next/server';
import { newcastleCoursesReal } from '@/data/newcastle-courses-real';
import { latestOf } from '@/lib/sitemap-lastmod';

const BASE = 'https://study.jaivikoverseasconsultants.com';
const UNI_SLUG = 'university-of-newcastle-australia';

export const dynamic = 'force-static';

/**
 * University of Newcastle-only sitemap, submitted to Search Console alongside /sitemap.xml and
 * /sitemap-courses.xml (which both already list these same URLs — duplicate listing across
 * sitemaps is the established pattern here, see sitemap-courses.xml's own header comment).
 *
 * Why this one gets its own file (2026-10-04, by user request): every other Bucket-A university's
 * facts come from an official source; Newcastle's come ONLY from a partner-platform list (see
 * data/newcastle-courses-real.ts's header comment for the full reasoning). That makes it the one
 * university most likely to need a correction the moment an official source becomes reachable —
 * a changed fee, a found CRICOS code, a dropped/renamed programme. Keeping its URL list in one
 * small, dedicated file means that future fix is easy to find and easy to re-submit to Search
 * Console on its own, without touching or re-crawling the rest of the site's sitemap.
 *
 * Source of truth: data/newcastle-courses-real.ts, generated by scripts/gen-newcastle.js. Update
 * the CSV + re-run that script, then this file's output updates automatically — nothing here
 * should be hand-edited.
 */
export async function GET() {
  const lastmod = latestOf(
    `app/universities/${UNI_SLUG}/courses/[slug]/page.tsx`,
    `app/universities/${UNI_SLUG}/courses/page.tsx`,
    'data/newcastle-courses-real.ts',
    'scripts/gen-newcastle.js',
    'components/CourseRichContent.tsx',
  );
  const lastmodStr = lastmod?.toISOString().split('T')[0];

  const entries: { url: string; priority: string }[] = [
    { url: `${BASE}/universities/${UNI_SLUG}`, priority: '0.9' },
    { url: `${BASE}/universities/${UNI_SLUG}/courses`, priority: '0.6' },
    ...newcastleCoursesReal.map((c) => ({
      url: `${BASE}/universities/${UNI_SLUG}/courses/${c.slug}`,
      priority: '0.8',
    })),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.map(({ url, priority }) => `  <url>
    <loc>${url}</loc>${lastmodStr ? `
    <lastmod>${lastmodStr}</lastmod>` : ''}
    <changefreq>monthly</changefreq>
    <priority>${priority}</priority>
  </url>`).join('\n')}
</urlset>`;

  return new NextResponse(xml, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=86400, s-maxage=86400',
    },
  });
}
