import type { MetadataRoute } from 'next';
import { universities, countries } from '@/data/universities';
import { courses, courseCategories } from '@/data/courses';
import { utsCourses } from '@/data/uts-courses';

// AU university course imports — generated by overnight scraper
let cduCourses: any[] = [];
let swinburneCourses: any[] = [];
let kaplanCourses: any[] = [];
let notredameCourses: any[] = [];
let vuSydneyCourses: any[] = [];
let cquCourses: any[] = [];
let jcuBrisbaneCourses: any[] = [];
let murdochCourses: any[] = [];
let flindersCourses: any[] = [];
let utasCourses: any[] = [];
let griffithCourses: any[] = [];
let latrobeCourses: any[] = [];
let deakinCourses: any[] = [];

try { cduCourses = require('@/data/cdu-courses').cduCourses as any[]; } catch {}
try { swinburneCourses = require('@/data/swinburne-courses').swinburneCourses as any[]; } catch {}
try { kaplanCourses = require('@/data/kaplan-courses').kaplanCourses as any[]; } catch {}
try { notredameCourses = require('@/data/notredame-courses').notredameCourses as any[]; } catch {}
try { vuSydneyCourses = require('@/data/vu-sydney-courses').vu_sydneyCourses as any[]; } catch {}
try { cquCourses = require('@/data/cqu-courses').cquCourses as any[]; } catch {}
try { jcuBrisbaneCourses = require('@/data/jcu-brisbane-courses').jcu_brisbaneCourses as any[]; } catch {}
try { murdochCourses = require('@/data/murdoch-courses').murdochCourses as any[]; } catch {}
try { flindersCourses = require('@/data/flinders-courses').flindersCourses as any[]; } catch {}
try { utasCourses = require('@/data/utas-courses').utasCourses as any[]; } catch {}
try { griffithCourses = require('@/data/griffith-courses').griffithCourses as any[]; } catch {}
try { latrobeCourses = require('@/data/latrobe-courses').latrobeCourses as any[]; } catch {}
try { deakinCourses = require('@/data/deakin-courses').deakinCourses as any[]; } catch {}

const BASE = 'https://jaivikoverseasconsultants.com';

const AU_UNI_COURSES: Array<{ slug: string; courses: any[] }> = [
  { slug: 'uts-sydney',                  courses: utsCourses as any[] },
  { slug: 'charles-darwin-university',   courses: cduCourses },
  { slug: 'swinburne-university',        courses: swinburneCourses },
  { slug: 'kaplan-business-school',      courses: kaplanCourses },
  { slug: 'notre-dame-australia',        courses: notredameCourses },
  { slug: 'victoria-university-sydney',  courses: vuSydneyCourses },
  { slug: 'cquniversity',                courses: cquCourses },
  { slug: 'jcu-brisbane',               courses: jcuBrisbaneCourses },
  { slug: 'murdoch-university',          courses: murdochCourses },
  { slug: 'flinders-university',         courses: flindersCourses },
  { slug: 'university-of-tasmania',      courses: utasCourses },
  { slug: 'griffith-university',         courses: griffithCourses },
  { slug: 'la-trobe-university',         courses: latrobeCourses },
  { slug: 'deakin-university',           courses: deakinCourses },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    { url: BASE,                            lastModified: now, changeFrequency: 'weekly',  priority: 1.0 },
    { url: `${BASE}/universities`,          lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${BASE}/courses`,               lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${BASE}/course-finder`,         lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/book-counselling`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
  ];

  const universityPages = universities.map(u => ({
    url: `${BASE}/universities/${u.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.8,
  }));

  const countryPages = countries.map(c => ({
    url: `${BASE}/universities/country/${c.toLowerCase().replace(' ', '-')}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }));

  const coursePages = courses.map(c => ({
    url: `${BASE}/courses/${c.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.8,
  }));

  const categoryPages = courseCategories.map(cat => ({
    url: `${BASE}/courses/category/${encodeURIComponent(cat.toLowerCase().replace(/\s+/g, '-').replace(/[&]/g, 'and'))}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }));

  // AU university course index pages
  const auCourseIndexPages = AU_UNI_COURSES
    .filter(u => u.courses.length > 0)
    .map(u => ({
      url: `${BASE}/universities/${u.slug}/courses`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    }));

  // AU individual course detail pages
  const auCourseDetailPages = AU_UNI_COURSES.flatMap(u =>
    u.courses.map((c: any) => ({
      url: `${BASE}/universities/${u.slug}/courses/${c.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    }))
  );

  return [
    ...staticPages,
    ...universityPages,
    ...countryPages,
    ...coursePages,
    ...categoryPages,
    ...auCourseIndexPages,
    ...auCourseDetailPages,
  ];
}
