import type { MetadataRoute } from 'next';
import { universities, countries } from '@/data/universities';
import { courses, courseCategories } from '@/data/courses';
import { utsCourses } from '@/data/uts-courses';

// AU university course imports — generated by overnight scraper
let cduCourses: any[] = [];
let swinburneCourses: any[] = [];
let kaplanCourses: any[] = [];
let notredameCourses: any[] = [];
let vuSydneyCourses: any[] = [];
let cquCourses: any[] = [];
let jcuBrisbaneCourses: any[] = [];
let murdochCourses: any[] = [];
let flindersCourses: any[] = [];
let utasCourses: any[] = [];
let griffithCourses: any[] = [];
let latrobeCourses: any[] = [];
let deakinCourses: any[] = [];

try { cduCourses = require('@/data/cdu-courses').cduCourses as any[]; } catch {}
try { swinburneCourses = require('@/data/swinburne-courses').swinburneCourses as any[]; } catch {}
try { kaplanCourses = require('@/data/kaplan-courses').kaplanCourses as any[]; } catch {}
try { notredameCourses = require('@/data/notredame-courses').notredameCourses as any[]; } catch {}
try { vuSydneyCourses = require('@/data/vu-sydney-courses').vu_sydneyCourses as any[]; } catch {}
try { cquCourses = require('@/data/cqu-courses').cquCourses as any[]; } catch {}
try { jcuBrisbaneCourses = require('@/data/jcu-brisbane-courses').jcu_brisbaneCourses as any[]; } catch {}
try { murdochCourses = require('@/data/murdoch-courses').murdochCourses as any[]; } catch {}
try { flindersCourses = require('@/data/flinders-courses').flindersCourses as any[]; } catch {}
try { utasCourses = require('@/data/utas-courses').utasCourses as any[]; } catch {}
try { griffithCourses = require('@/data/griffith-courses').griffithCourses as any[]; } catch {}
try { latrobeCourses = require('@/data/latrobe-courses').latrobeCourses as any[]; } catch {}
try { deakinCourses = require('@/data/deakin-courses').deakinCourses as any[]; } catch {}

// UK university course imports
let manchesterCourses: any[] = [];
let birminghamCourses: any[] = [];
let leedsCourses: any[] = [];
let coventryCourses: any[] = [];
let middlesexCourses: any[] = [];
let brunelCourses: any[] = [];
let hertfordshireCourses: any[] = [];
let aruCourses: any[] = [];
let portsmouthCourses: any[] = [];
let northumbriaCourses: any[] = [];
let demontfortCourses: any[] = [];
let nottinghamtrentCourses: any[] = [];
let westlondonCourses: any[] = [];

try { manchesterCourses = require('@/data/manchester-courses').manchesterCourses as any[]; } catch {}
try { birminghamCourses = require('@/data/birmingham-courses').birminghamCourses as any[]; } catch {}
try { leedsCourses = require('@/data/leeds-courses').leedsCourses as any[]; } catch {}
try { coventryCourses = require('@/data/coventry-courses').coventryCourses as any[]; } catch {}
try { middlesexCourses = require('@/data/middlesex-courses').middlesexCourses as any[]; } catch {}
try { brunelCourses = require('@/data/brunel-courses').brunelCourses as any[]; } catch {}
try { hertfordshireCourses = require('@/data/hertfordshire-courses').hertfordshireCourses as any[]; } catch {}
try { aruCourses = require('@/data/aru-courses').aruCourses as any[]; } catch {}
try { portsmouthCourses = require('@/data/portsmouth-courses').portsmouthCourses as any[]; } catch {}
try { northumbriaCourses = require('@/data/northumbria-courses').northumbriaCourses as any[]; } catch {}
try { demontfortCourses = require('@/data/demontfort-courses').demontfortCourses as any[]; } catch {}
try { nottinghamtrentCourses = require('@/data/nottinghamtrent-courses').nottinghamtrentCourses as any[]; } catch {}
try { westlondonCourses = require('@/data/westlondon-courses').westlondonCourses as any[]; } catch {}

// CA university/college course imports
let windsorCourses: any[] = [];
let trentCourses: any[] = [];
let conestogaCourses: any[] = [];
let humberCourses: any[] = [];
let sheridanCourses: any[] = [];
let georgeBrownCourses: any[] = [];
let algonquinCourses: any[] = [];
let mohawkCourses: any[] = [];
let truCourses: any[] = [];
let unbcCourses: any[] = [];
let capilanoCourses: any[] = [];
let saitCourses: any[] = [];
let concordiaEdmontonCourses: any[] = [];
let acadiaCourses: any[] = [];
let cbuCourses: any[] = [];
let urCourses: any[] = [];
let saskPolyCourses: any[] = [];

try { windsorCourses = require('@/data/windsor-courses').windsorCourses as any[]; } catch {}
try { trentCourses = require('@/data/trent-courses').trentCourses as any[]; } catch {}
try { conestogaCourses = require('@/data/conestoga-courses').conestogaCourses as any[]; } catch {}
try { humberCourses = require('@/data/humber-courses').humberCourses as any[]; } catch {}
try { sheridanCourses = require('@/data/sheridan-courses').sheridanCourses as any[]; } catch {}
try { georgeBrownCourses = require('@/data/george-brown-courses').george_brownCourses as any[]; } catch {}
try { algonquinCourses = require('@/data/algonquin-courses').algonquinCourses as any[]; } catch {}
try { mohawkCourses = require('@/data/mohawk-courses').mohawkCourses as any[]; } catch {}
try { truCourses = require('@/data/tru-courses').truCourses as any[]; } catch {}
try { unbcCourses = require('@/data/unbc-courses').unbcCourses as any[]; } catch {}
try { capilanoCourses = require('@/data/capilano-courses').capilanoCourses as any[]; } catch {}
try { saitCourses = require('@/data/sait-courses').saitCourses as any[]; } catch {}
try { concordiaEdmontonCourses = require('@/data/concordia-edmonton-courses').concordia_edmontonCourses as any[]; } catch {}
try { acadiaCourses = require('@/data/acadia-courses').acadiaCourses as any[]; } catch {}
try { cbuCourses = require('@/data/cbu-courses').cbuCourses as any[]; } catch {}
try { urCourses = require('@/data/ur-courses').urCourses as any[]; } catch {}
try { saskPolyCourses = require('@/data/sask-poly-courses').sask_polyCourses as any[]; } catch {}

const CA_UNI_COURSES: Array<{ slug: string; courses: any[] }> = [
  { slug: 'university-of-windsor',         courses: windsorCourses },
  { slug: 'trent-university',              courses: trentCourses },
  { slug: 'conestoga-college',             courses: conestogaCourses },
  { slug: 'humber-college',               courses: humberCourses },
  { slug: 'sheridan-college',              courses: sheridanCourses },
  { slug: 'george-brown-college',         courses: georgeBrownCourses },
  { slug: 'algonquin-college',            courses: algonquinCourses },
  { slug: 'mohawk-college',               courses: mohawkCourses },
  { slug: 'thompson-rivers-university',   courses: truCourses },
  { slug: 'university-of-northern-bc',    courses: unbcCourses },
  { slug: 'capilano-university',          courses: capilanoCourses },
  { slug: 'sait',                         courses: saitCourses },
  { slug: 'concordia-university-edmonton', courses: concordiaEdmontonCourses },
  { slug: 'acadia-university',            courses: acadiaCourses },
  { slug: 'cape-breton-university',       courses: cbuCourses },
  { slug: 'university-of-regina',         courses: urCourses },
  { slug: 'saskatchewan-polytechnic',     courses: saskPolyCourses },
];

const UK_UNI_COURSES: Array<{ slug: string; courses: any[] }> = [
  { slug: 'university-of-manchester',    courses: manchesterCourses },
  { slug: 'university-of-birmingham',    courses: birminghamCourses },
  { slug: 'university-of-leeds',         courses: leedsCourses },
  { slug: 'coventry-university',         courses: coventryCourses },
  { slug: 'middlesex-university',        courses: middlesexCourses },
  { slug: 'brunel-university-london',    courses: brunelCourses },
  { slug: 'university-of-hertfordshire', courses: hertfordshireCourses },
  { slug: 'anglia-ruskin-university',    courses: aruCourses },
  { slug: 'university-of-portsmouth',    courses: portsmouthCourses },
  { slug: 'northumbria-university',      courses: northumbriaCourses },
  { slug: 'de-montfort-university',      courses: demontfortCourses },
  { slug: 'nottingham-trent-university', courses: nottinghamtrentCourses },
  { slug: 'university-of-west-london',   courses: westlondonCourses },
];

const BASE = 'https://study.jaivikoverseasconsultants.com';

const AU_UNI_COURSES: Array<{ slug: string; courses: any[] }> = [
  { slug: 'uts-sydney',                  courses: utsCourses as any[] },
  { slug: 'charles-darwin-university',   courses: cduCourses },
  { slug: 'swinburne-university',        courses: swinburneCourses },
  { slug: 'kaplan-business-school',      courses: kaplanCourses },
  { slug: 'notre-dame-australia',        courses: notredameCourses },
  { slug: 'victoria-university-sydney',  courses: vuSydneyCourses },
  { slug: 'cquniversity',                courses: cquCourses },
  { slug: 'jcu-brisbane',               courses: jcuBrisbaneCourses },
  { slug: 'murdoch-university',          courses: murdochCourses },
  { slug: 'flinders-university',         courses: flindersCourses },
  { slug: 'university-of-tasmania',      courses: utasCourses },
  { slug: 'griffith-university',         courses: griffithCourses },
  { slug: 'la-trobe-university',         courses: latrobeCourses },
  { slug: 'deakin-university',           courses: deakinCourses },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    { url: BASE,                            lastModified: now, changeFrequency: 'weekly',  priority: 1.0 },
    { url: `${BASE}/universities`,          lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${BASE}/courses`,               lastModified: now, changeFrequency: 'weekly',  priority: 0.9 },
    { url: `${BASE}/course-finder`,         lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${BASE}/book-counselling`,      lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
  ];

  const universityPages = universities.map(u => ({
    url: `${BASE}/universities/${u.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.8,
  }));

  const countryPages = countries.map(c => ({
    url: `${BASE}/universities/country/${c.toLowerCase().replace(' ', '-')}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }));

  const coursePages = courses.map(c => ({
    url: `${BASE}/courses/${c.slug}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.8,
  }));

  const categoryPages = courseCategories.map(cat => ({
    url: `${BASE}/courses/category/${encodeURIComponent(cat.toLowerCase().replace(/\s+/g, '-').replace(/[&]/g, 'and'))}`,
    lastModified: now,
    changeFrequency: 'monthly' as const,
    priority: 0.7,
  }));

  // AU university course index pages
  const auCourseIndexPages = AU_UNI_COURSES
    .filter(u => u.courses.length > 0)
    .map(u => ({
      url: `${BASE}/universities/${u.slug}/courses`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    }));

  // AU individual course detail pages
  const auCourseDetailPages = AU_UNI_COURSES.flatMap(u =>
    u.courses.map((c: any) => ({
      url: `${BASE}/universities/${u.slug}/courses/${c.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    }))
  );

  // CA university/college course index pages
  const caCourseIndexPages = CA_UNI_COURSES
    .filter(u => u.courses.length > 0)
    .map(u => ({
      url: `${BASE}/universities/${u.slug}/courses`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    }));

  // CA individual course detail pages
  const caCourseDetailPages = CA_UNI_COURSES.flatMap(u =>
    u.courses.map((c: any) => ({
      url: `${BASE}/universities/${u.slug}/courses/${c.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    }))
  );

  // UK university course index pages
  const ukCourseIndexPages = UK_UNI_COURSES
    .filter(u => u.courses.length > 0)
    .map(u => ({
      url: `${BASE}/universities/${u.slug}/courses`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    }));

  // UK individual course detail pages
  const ukCourseDetailPages = UK_UNI_COURSES.flatMap(u =>
    u.courses.map((c: any) => ({
      url: `${BASE}/universities/${u.slug}/courses/${c.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    }))
  );

  return [
    ...staticPages,
    ...universityPages,
    ...countryPages,
    ...coursePages,
    ...categoryPages,
    ...auCourseIndexPages,
    ...auCourseDetailPages,
    ...caCourseIndexPages,
    ...caCourseDetailPages,
    ...ukCourseIndexPages,
    ...ukCourseDetailPages,
  ];
}
