import type { Metadata } from 'next';
import Link from 'next/link';
import { buildMetadata } from '@/lib/seo';
import { yorkuCourses } from '@/data/yorku-courses';
import LeadForm from '@/components/LeadForm';
import JsonLd from '@/components/JsonLd';
import { feeDisplay, isFeeVerified, verifiedAvgFee } from '@/lib/fee-verification';
import { publishedEnglishTests } from '@/lib/english-verification';
import { RATE_TO_INR, courseAnnualINRLakh } from '@/lib/currency';

// Generated by scripts/gen-canada-wave-routes.js — edit the generator, not this file.

const UNIVERSITY_SLUG = 'york-university';

export const metadata: Metadata = buildMetadata({
  title: 'York University Courses — Fees & Requirements 2026',
  description: `York University — ${(yorkuCourses as unknown as any[]).length} programmes for international students in Toronto, Canada. Free admission guidance from Jaivik Overseas Consultants.`,
  path: '/universities/york-university/courses',
  keywords: ['York courses', 'York University international', 'study in Canada', 'Toronto'],
});

const levelOrder = ['Bachelor', 'Honours Bachelor', 'Advanced Diploma', 'Diploma', 'Certificate', 'Graduate Certificate', 'Masters', 'Master', 'Graduate Diploma', 'PhD'];

export default function CoursesPage() {
  const courses = yorkuCourses as unknown as any[];
  const groups: Record<string, any[]> = {};
  courses.forEach((c) => { (groups[c.level] = groups[c.level] || []).push(c); });
  const avgFee = verifiedAvgFee(courses, 'annualCAD');
  const verified = courses.filter((c) => isFeeVerified(c) && Number(c.annualUSD) > 0);
  const avgFeeUSD = verified.length ? Math.round(verified.reduce((s, c) => s + Number(c.annualUSD), 0) / verified.length) : 0;

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How many programmes does York University offer for international students?',
        acceptedAnswer: { '@type': 'Answer', text: `York University lists ${courses.length} programmes in our course finder, each linked to its official page.` },
      },
      ...(avgFeeUSD > 0 ? [{
        '@type': 'Question',
        name: 'What is the average international tuition at York University?',
        acceptedAnswer: { '@type': 'Answer', text: `Across the ${verified.length} programmes where York University publishes an international fee, the average is about ${avgFeeUSD.toLocaleString()} USD (≈ ₹${(avgFeeUSD * RATE_TO_INR.USD / 100000).toFixed(1)}L) a year.` },
      }] : []),
      {
        '@type': 'Question',
        name: 'How can Indian students apply to York University?',
        acceptedAnswer: { '@type': 'Answer', text: 'Indian students can apply to York University through Jaivik Overseas Consultants — free application guidance, SOP writing, and visa assistance included.' },
      },
    ],
  };

  const courseListSchema = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: 'York University — Courses for International Students',
    numberOfItems: courses.length,
    itemListElement: courses.slice(0, 5).map((c, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      item: {
        '@type': 'Course',
        name: c.name,
        provider: { '@type': 'CollegeOrUniversity', name: 'York University' },
        ...(isFeeVerified(c) && Number(c.annualUSD) > 0 ? { offers: { '@type': 'Offer', price: Number(c.annualUSD), priceCurrency: 'USD' } } : {}),
        educationalLevel: c.level ?? c.studyLevel,
      },
    })),
  };

  const schema = {
    '@context': 'https://schema.org',
    '@type': 'CollegeOrUniversity',
    name: 'York University',
    sameAs: 'https://www.yorku.ca',
    address: { '@type': 'PostalAddress', addressLocality: 'Toronto', addressRegion: 'Ontario', addressCountry: 'CA' },
  };

  return (
    <>
      <JsonLd data={schema} />
      <JsonLd data={faqSchema} />
      <JsonLd data={courseListSchema} />

      <section className="bg-gradient-to-br from-brand-700 to-brand-900 text-white py-14 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="flex items-center gap-2 text-blue-200 text-xs mb-4">
            <Link href="/" className="hover:text-white">Home</Link> /
            <Link href="/universities" className="hover:text-white">Universities</Link> /
            <Link href="/universities/country/canada" className="hover:text-white">Canada</Link> /
            <Link href="/universities/york-university" className="hover:text-white">York</Link> /
            <span className="text-white">Courses</span>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
            <div className="lg:col-span-2">
              <div className="inline-flex items-center gap-2 bg-gold-500/20 text-gold-400 text-xs font-semibold px-3 py-1.5 rounded-full mb-4">
                🇨🇦 Toronto, Ontario, Canada
              </div>
              <h1 className="text-3xl md:text-4xl font-bold mb-3">York University — International Courses</h1>
              <p className="text-blue-200 text-lg mb-5">
                {courses.length} programmes{avgFee > 0 ? ` · average published fee CAD $${avgFee.toLocaleString()}/yr` : ''}
              </p>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                {[
                  { label: 'Programmes', value: String(courses.length) },
                  { label: 'Published intl. fees', value: `${verified.length} of ${courses.length}` },
                  { label: 'Avg annual fee', value: avgFee > 0 ? `$${Math.round(avgFee / 1000)}K CAD` : 'On request' },
                ].map((s) => (
                  <div key={s.label} className="bg-white/10 rounded-xl p-3 text-center">
                    <p className="text-xl font-bold">{s.value}</p>
                    <p className="text-xs text-blue-200 mt-1">{s.label}</p>
                  </div>
                ))}
              </div>
            </div>
            <div className="bg-white rounded-2xl p-5">
              <LeadForm source="yorku-courses-index" defaultCountry="Canada" compact />
            </div>
          </div>
        </div>
      </section>

      <div className="max-w-7xl mx-auto px-4 py-10 grid grid-cols-1 lg:grid-cols-4 gap-8">
        <div className="lg:col-span-3 space-y-10">
          {Object.entries(groups)
            .sort(([a], [b]) => (levelOrder.indexOf(a) === -1 ? 99 : levelOrder.indexOf(a)) - (levelOrder.indexOf(b) === -1 ? 99 : levelOrder.indexOf(b)))
            .map(([level, lvCourses]) => (
            <div key={level}>
              <h2 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-2">
                {level} Programmes
                <span className="text-xs bg-brand-100 text-brand-700 px-2 py-1 rounded-full font-normal">{lvCourses.length}</span>
              </h2>
              <div className="space-y-3">
                {lvCourses.slice().sort((a, b) => a.name.localeCompare(b.name)).map((c) => (
                  <Link key={c.slug} href={`/universities/york-university/courses/${c.slug}`}
                    className="bg-white rounded-xl p-4 border border-gray-100 hover:shadow-md hover:border-brand-200 transition-all flex items-center justify-between group">
                    <div className="flex-1 min-w-0">
                      <p className="font-semibold text-gray-900 group-hover:text-brand-700 text-sm leading-snug">{c.name}</p>
                      <p className="text-xs text-gray-500 mt-1">{c.duration} · {c.campus}</p>
                    </div>
                    <div className="ml-4 text-right flex-shrink-0">
                      <p className="text-sm font-bold text-brand-700">{isFeeVerified(c) ? `${feeDisplay(c, c.annualCAD, 'CAD')}/yr` : 'Fee on request'}</p>
                      {isFeeVerified(c) && <p className="text-xs text-gray-400">≈ ₹{courseAnnualINRLakh(c, 1) ?? '0'}L/yr</p>}
                      {publishedEnglishTests(UNIVERSITY_SLUG, c as never).some((t) => t.label === 'IELTS Academic') && <p className="text-xs text-gray-500">IELTS {c.ieltsMin}+</p>}
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          ))}
        </div>

        <div>
          <div className="sticky top-20 space-y-5">
            <LeadForm source="yorku-courses-sidebar" defaultCountry="Canada" />
          </div>
        </div>
      </div>
    </>
  );
}
