// GENERATED by scripts/gen-english-published.js — do not edit by hand.
//
// Which English tests each university PUBLISHES a score for, from its own English-requirements
// page. `false` means: we looked, and the university did not state a score for that test — so the
// value carried on the course row is our house default and must never be printed as a requirement.
//
// Absent university = unknown, and lib/english-verification treats unknown as publishing all three
// (same deliberate default as lib/fee-verification: silence here must not blank out the ~42
// universities whose real per-course IELTS varies). Add universities here as they are checked.
//
// Canada rows come from data/wave-canada/institution-english.json (16 universities,
// generated 2026-09-21).

export interface EnglishPublication {
  /** the university's own page states an IELTS score */
  ielts: boolean;
  toefl: boolean;
  pte: boolean;
  /** granularity of the published figure */
  scope: string;
  sourceUrl: string | null;
  /** why nothing is publishable, when all three are false */
  note: string | null;
}

export const ENGLISH_PUBLISHED: Record<string, EnglishPublication> = {
  'algonquin-college': { ielts: true, toefl: true, pte: false, scope: 'institution-wide', sourceUrl: 'https://www.algonquincollege.com/international/admission-requirements/', note: null },
  'dalhousie-university': { ielts: false, toefl: false, pte: false, scope: 'institution-wide', sourceUrl: 'https://www.dal.ca/admissions/undergraduate/requirements/english-language-requirements.html', note: null },
  'durham-college': { ielts: true, toefl: false, pte: true, scope: 'institution-wide', sourceUrl: 'https://durhamcollege.ca/international/english-language-proficiency', note: null },
  'kwantlen-polytechnic-university': { ielts: false, toefl: false, pte: false, scope: 'institution-wide', sourceUrl: 'https://www.kpu.ca/pathway', note: 'Page reached was a PATHWAY page, not the direct-entry requirement (bands seen: 5.5 / 6.0).' },
  'queens-university': { ielts: false, toefl: false, pte: false, scope: 'institution-wide', sourceUrl: 'https://www.queensu.ca/admission/applicants/english-proficiency', note: 'Tiered by faculty/programme group (bands seen: 6.5 / 6.0 / 5.5). No stated institution-wide default.' },
  'red-river-college-polytechnic': { ielts: false, toefl: false, pte: false, scope: 'institution-wide', sourceUrl: 'https://www.rrc.ca/international/future-students/admission-requirements/', note: null },
  'toronto-metropolitan-university': { ielts: true, toefl: false, pte: true, scope: 'institution-wide', sourceUrl: 'https://www.torontomu.ca/admissions/undergraduate/requirements/english-language/', note: null },
  'university-of-alberta': { ielts: false, toefl: false, pte: false, scope: 'institution-wide', sourceUrl: 'https://www.ualberta.ca/en/admissions/undergraduate/admission/admission-requirements/english-language-requirement/index.html', note: null },
  'university-of-guelph': { ielts: true, toefl: true, pte: true, scope: 'institution-wide', sourceUrl: 'https://admission.uoguelph.ca/englishproficiency', note: null },
  'university-of-manitoba': { ielts: false, toefl: false, pte: false, scope: 'institution-wide', sourceUrl: 'https://umanitoba.ca/explore/undergraduate-admissions/requirements/english-language-proficiency-requirements', note: 'Published for UNDERGRADUATE admission only — the page states graduate applicants must check each programme. Applied to the 200 undergraduate rows as englishVerified (scripts/apply-canada-published-fees.js); nothing publishes university-wide.' },
  'university-of-new-brunswick': { ielts: true, toefl: true, pte: true, scope: 'institution-wide', sourceUrl: 'https://www.unb.ca/international/admission/english.html', note: null },
  'university-of-ottawa': { ielts: false, toefl: false, pte: false, scope: 'institution-wide', sourceUrl: 'https://www.uottawa.ca/study/undergraduate-studies/admission/language-requirements', note: null },
  'university-of-victoria': { ielts: false, toefl: false, pte: false, scope: 'institution-wide', sourceUrl: 'https://www.uvic.ca/undergraduate/admissions/admission-requirements/english-language-requirements/index.php', note: null },
  'university-of-waterloo': { ielts: true, toefl: false, pte: true, scope: 'institution-wide', sourceUrl: 'https://uwaterloo.ca/future-students/admissions/english-language-requirements', note: null },
  'university-of-windsor': { ielts: false, toefl: false, pte: false, scope: 'institution-wide', sourceUrl: 'https://www.uwindsor.ca/registrar/english-language-requirements', note: null },
  'york-university': { ielts: false, toefl: false, pte: false, scope: 'institution-wide', sourceUrl: 'https://futurestudents.yorku.ca/requirements/language-tests', note: 'Tiered, and the low bands belong to the ESL/pathway route (bands seen: 6.5 / 5.5 / 6 / 5).' },
};
